config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints subdomain: 'kiosk' do
    devise_for :users, controllers: {
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }
    root to: 'kiosk_home#index', as: 'kiosk_root'
    get '/kiosk', to: 'kiosk#index'
    get '/menu', to: 'menu#index', as: 'menu'

    resources :stores, except: [:index, :destroy]
    resources :bills
    resources :transactions, only: [:show, :index]
    resources :rewards, only: [:index]
    resources :redemptions
    resources :redemption_flows
  end

  constraints subdomain: 'customer' do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      passwords: 'customers/passwords'
    }

    namespace :customers do
      resources :sign_up_flow
      resources :recovery_flow
    end

    root to: 'customer#index', as: 'customer_root'
  end

  root to: 'home#index', as: 'marketing_root'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  validates_presence_of :name, :contact_number
  validates :name, length: { in: 6..30 }, allow_blank: true
  has_many :transactions, -> { order(created_at: :desc) }
  has_many :redemption_flows, -> { order(created_at: :desc) }

  before_save :set_unique_id

  validates_uniqueness_of :owner_id, message: "Only one store per user"

  def redemptions
    transactions.where(type: 'Redemption')
  end

  def bills
    transactions.where(type: 'Bill')
  end

  def set_unique_id
    return if unique_id

    self.unique_id = SecureRandom.uuid
  end
end

app/controllers/stores_controller.rb
class StoresController < KioskApplicationController
  load_and_authorize_resource
  skip_before_action :check_for_store

  # GET /redemptions/1 or /redemptions/1.json
  def show
  end

  # GET /stores/new
  def new
    if current_user.owned_store.present?
      redirect_to edit_store_path(current_user.owned_store), alert: 'You can have only one store.'
    end
  end

  # GET /stores/1/edit
  def edit; end

  # POST /stores
  # POST /stores.json
  def create
    respond_to do |format|
      if @store.save
        format.html { redirect_to kiosk_root_path, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: kiosk_root_path }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to edit_store_path(@store), notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: kiosk_root_path }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def store_params
    params.fetch(:store).permit(:name, :discount_percentage, :contact_number).merge(owner: current_user)
  end
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true, url: store.new_record? ? stores_path : store_path) do |form| %>
  <% if store.errors.any? %>
    <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
      <p class="font-bold">Oops!</p>
      <p><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</p>
      <% store.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="input-group">
    <%= form.label :name, "Store Name" %>
    <%= form.text_field :name, class: 'input', placeholder: 'Store name' %>
  </div>

  <div class="input-group">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number, class: 'input', placeholder: 'Contact Number' %>
  </div>

  <div class="input-group">
    <%= form.label :discount_percentage, "Discount Percentage" %>
    <%= form.text_field :discount_percentage, type: 'number', class: 'input', placeholder: 'Discount Percentage' %>
  </div>



  <div class="input-group">
    <%= form.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<div class="w-full max-w-3xl mx-auto my-8">
  <div class="bg-white border border-gray-300 rounded-lg px-8 pt-6 pb-8">
    <h1 class="pt-4 mb-8 text-4xl font-bold heading">Edit Store</h1>
    <%= render 'form', store: @store %>
  </div>
</div>

app/views/stores/index.html.erb
<div class="w-full max-w-xl">
  <div class="bg-white border border-gray-300 rounded-lg px-8 pt-6 pb-8">
    <div class="d-flex align-items-center justify-content-between">
      <h2 class="pt-4 mb-8 text-4xl font-bold heading">Stores</h2>
    </div>
    <div class="table-responsive-xl w-full">
      <table class="table">
        <tbody>
        <% @stores.each do |store| %>
          <tr class="border border-gray-200 p-4">
            <td class="p-4">
              <%= store.name %>
            </td>
            <td class="p-4">
              <%= link_to "Edit", edit_store_path(store) %>
              <% if store != current_user.owned_store %>
                | <%= link_to "Make Default", set_as_preferred_store_path(store) %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <%= link_to 'New Store', new_store_path, class: 'btn btn-default mt-4' %>
  </div>
</div>

app/views/stores/new.html.erb
<div class="w-full max-w-3xl mx-auto my-8">
  <div class="bg-white border border-gray-300 rounded-lg px-8 pt-6 pb-8">
    <h1 class="pt-4 mb-2 text-4xl font-bold heading">New Store</h1>
    <h2 class="pt-2 mb-8 text-lg">
      You need to setup the store to access other features of the app.
    </h2>
    <%= render 'form', store: @store %>
  </div>
</div>

app/views/stores/show.html.erb
<p><%= @store.name %></p>
<%= link_to 'Edit', edit_store_path(@store.id) %>