config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints subdomain: 'kiosk' do
    devise_for :users, controllers: {
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }
    root to: 'kiosk_home#index', as: 'kiosk_root'
    get '/kiosk', to: 'kiosk#index'
    get '/menu', to: 'menu#index', as: 'menu'

    resources :stores, except: [:index, :destroy]
    resources :bills
    resources :transactions, only: [:show, :index]
    resources :rewards, only: [:index]
    resources :redemptions
    resources :redemption_flows
  end

  constraints subdomain: 'customer' do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      passwords: 'customers/passwords'
    }

    namespace :customers do
      resources :sign_up_flow
      resources :recovery_flow
    end

    root to: 'customer#index', as: 'customer_root'
  end

  root to: 'home#index', as: 'marketing_root'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reward.rb
class Reward < Transaction
end

app/controllers/rewards_controller.rb
class RewardsController < KioskApplicationController
  load_and_authorize_resource

  # GET /rewards or /rewards.json
  def index
    @rewards = filtered_by_number
  end

  private

  def filtered_by_number
    return all_rewards unless params[:number].present?

    all_rewards.where(phone_number: params[:number])
  end

  def all_rewards
    current_user.owned_store.rewards
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_with(model: reward) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rewards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= link_to 'Show', reward %></td>
        <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
        <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>