config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints subdomain: 'kiosk' do
    devise_for :users, controllers: {
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }
    root to: 'kiosk_home#index', as: 'kiosk_root'
    get '/kiosk', to: 'kiosk#index'
    get '/menu', to: 'menu#index', as: 'menu'

    resources :stores, except: [:index, :destroy]
    resources :bills
    resources :transactions, only: [:show, :index]
    resources :rewards, only: [:index]
    resources :redemptions
    resources :redemption_flows
  end

  constraints subdomain: 'customer' do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      passwords: 'customers/passwords'
    }

    namespace :customers do
      resources :sign_up_flow
      resources :recovery_flow
    end

    root to: 'customer#index', as: 'customer_root'
  end

  root to: 'home#index', as: 'marketing_root'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :lockable, :validatable, :authentication_keys => [:phone]
  self.lock_strategy = :failed_attempts
  self.unlock_strategy = :none
  self.maximum_attempts = 5

  validates_uniqueness_of :phone

  has_many :transactions, foreign_key: :phone_number, primary_key: :phone

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end

  def remember_me
    true
  end
end

app/controllers/customer_controller.rb
class CustomerController < CustomerApplicationController
  def index
    @transactions = current_customer
                      .transactions
                      .where(type: 'Reward')
                      .joins(:store)
                      .select(:store_id, 'sum(amount) as total_points')
                      .group(:store_id)
                      .each_with_object([]) do |(k, _), memo|
      store = Store.find(k[:store_id])
      points = k[:total_points]
      visits = Bill.where(phone_number: current_customer.phone, store: store).count
      memo << { store: store, points: points, visits: visits }
    end
    p @transactions
  end

  private

  def store
    return unless params[:org_id]
    Store.where(unique_id: params[:org_id]).first
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  def unlockable?(resource)
    resource.respond_to?(:unlock_access!)
  end
end

app/controllers/customers/recovery_flow_controller.rb
class Customers::RecoveryFlowController < ApplicationController
  include Wicked::Wizard
  steps :mobile_input, :verify_otp

  layout 'customer_application'

  def show
    session[:recovery_flow_id] ||= SecureRandom.uuid
    if params[:reset].present?
      session[:recovery_flow_id] = SecureRandom.uuid
    end

    @auth_flow = AuthFlow.where(flow_id: session[:recovery_flow_id]).first_or_create!
    if step == :mobile_input && !@auth_flow.unverified?
      skip_step
    end

    if step == :verify_otp
      if @auth_flow.unverified?
        jump_to(:mobile_input)
      end
      if @auth_flow.otp_verification?
        skip_step
      end
    end

    render_wizard
  end

  def update
    @auth_flow = AuthFlow.find_by(flow_id: session[:recovery_flow_id])

    case step
    when :mobile_input
      @auth_flow.assign_attributes(customer_params)
      @auth_flow.assign_attributes(status: AuthFlow.statuses[:captcha_verification])
      if verify_recaptcha
        @auth_flow.assign_attributes(verified: true, otp: '121212')
      end
    when :verify_otp
      @auth_flow.assign_attributes(customer_params)
      @auth_flow.assign_attributes(status: AuthFlow.statuses[:otp_verification])

      unless @auth_flow.valid?
        @auth_flow.increment!(:attempts, 1)
      end
    end

    render_wizard(@auth_flow)
  end

  def finish_wizard_path
    @auth_flow = AuthFlow.find_by(flow_id: session[:recovery_flow_id])
    customer = Customer.find_by_phone(@auth_flow.phone)
    unless customer
      return customers_sign_up_flow_path(:mobile_input)
    end

    token = customer.send(:set_reset_password_token)
    @auth_flow.destroy!
    edit_customer_password_path(reset_password_token: token)
  end

  private

  def customer_params
    params.require(:auth_flow).permit(:phone, :current_otp).merge(flow: 'recover')
  end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @auth_flow = AuthFlow.find_by(flow_id: session[:sign_up_flow_id])
    unless @auth_flow && @auth_flow.otp_verification?
      redirect_to customers_sign_up_flow_path(:mobile_input)
      return
    end

    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  #

  def sign_up_params
    @auth_flow = AuthFlow.find_by(flow_id: session[:sign_up_flow_id])

    params.require(:customer).permit(:password, :password_confirmation).merge(phone: @auth_flow&.phone)
  end


  def after_sign_up_path_for(resource)
    @auth_flow = AuthFlow.find_by(flow_id: session[:sign_up_flow_id])
    @auth_flow.destroy!

    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/sign_up_flow_controller.rb
class Customers::SignUpFlowController < ApplicationController
  layout 'customer_application'
  include Wicked::Wizard

  steps :mobile_input, :verify_otp

  def show
    session[:flow_id] ||= SecureRandom.uuid
    if params[:reset].present?
      session[:flow_id] = SecureRandom.uuid
    end

    @auth_flow = AuthFlow.where(flow_id: session[:flow_id]).first_or_create!
    if step == :mobile_input && !@auth_flow.unverified?
      skip_step
    end

    if step == :verify_otp && !@auth_flow.unverified? && !@auth_flow.captcha_verification?
      skip_step
    end

    render_wizard
  end

  def update
    @auth_flow = AuthFlow.find_by(flow_id: session[:flow_id])

    case step
    when :mobile_input
      @auth_flow.assign_attributes(customer_params)
      @auth_flow.assign_attributes(status: AuthFlow.statuses[:captcha_verification])
      if verify_recaptcha
        @auth_flow.assign_attributes(verified: true, otp: '121212')
      end
    when :verify_otp
      @auth_flow.assign_attributes(customer_params)
      @auth_flow.assign_attributes(status: AuthFlow.statuses[:otp_verification])

      unless @auth_flow.valid?
        @auth_flow.increment!(:attempts, 1)
      end
    end

    render_wizard(@auth_flow)
  end

  def finish_wizard_path
    new_customer_registration_path
  end

  private
  def customer_params
    params.require(:auth_flow).permit(:phone, :current_otp)
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/customers/recovery_flow/mobile_input.html.erb
<div class="w-full max-w-3xl mx-auto my-8">
  <div class="bg-white border border-gray-300 rounded-lg px-8 pt-6 pb-8">
    <h2 class="pt-4 mb-1 text-4xl font-bold heading">Recover Password</h2>
    <h3 class="pt-2 mb-8 text-xl uppercase font-bold heading">Step 1/3:</h3>

    <%= form_for @auth_flow, url: wizard_path, method: :put do |f| %>
      <% if @auth_flow.errors.any? %>
        <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <% @auth_flow.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        </div>
      <% end %>

      <div class="input-group">
        <%= f.label :phone, "Mobile number (without +91):", class:"label" %>
        <%= f.text_field :phone, class:"input" %>
      </div>

      <%= recaptcha_tags %>
      <br />
      <div class="input-group">
        <%= f.submit "Get OTP", class: "btn btn-default" %>
      </div>

      <hr class="mt-6 border" />

      <div class="flex flex-wrap flex-row items-center justify-start">
        <%= link_to "Log in", new_session_path('customer'), class: "block py-2 text-gray-700 underline hover:no-underline" %>
         |
        <%= link_to "Sign up", new_registration_path('customer'), class: "block py-2 text-gray-700 underline hover:no-underline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/customers/recovery_flow/verify_otp.erb
<div class="w-full max-w-3xl mx-auto my-8">
  <div class="bg-white border border-gray-300 rounded-lg px-8 pt-6 pb-8">
    <h2 class="pt-4 mb-1 text-4xl font-bold heading">Recover Password</h2>
    <h3 class="pt-2 mb-8 text-xl uppercase font-bold heading">Step 2/3:</h3>

    <%= form_for @auth_flow, url: wizard_path, method: :put do |f| %>
      <% if @auth_flow.errors.any? %>
        <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <% @auth_flow.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        </div>
      <% end %>

      <div class="input-group">
        <%= f.label :current_otp, "6 digit OTP:", class:"label" %>
        <%= f.text_field :current_otp, class:"input" %>
      </div>

      <%= f.hidden_field :phone  %>
      <div class="input-group">
        <%= f.submit "Go", class: "btn btn-default" %>
      </div>

      <hr class="mt-6 border" />

      <div class="flex flex-wrap flex-row items-center justify-start">
        <%= link_to "Log in", new_session_path('customer'), class: "block py-2 text-gray-700 underline hover:no-underline" %> |
        <%= link_to "Reset", customers_recovery_flow_path(:mobile_input, reset: true), class: "block py-2 text-gray-700 underline hover:no-underline" %>
      </div>
  <% end %>
  </div>
</div>